<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ameet" failures="15" tests="16" name="Test" time="74.34" errors="0" timestamp="2025-01-03T19:01:05 IST">
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="createAppointmentTest" time="8.214">
    <failure type="java.lang.AssertionError" message="createAppointmentWithAuth must be implemented using Rest Assured methods only. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: createAppointmentWithAuth must be implemented using Rest Assured methods only. expected [true] but found [false]
at testcases.RestAssured_TestCases_PL2.createAppointmentTest(RestAssured_TestCases_PL2.java:53)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- createAppointmentTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="searchPatientTest" time="0.016">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.searchPatientTest(RestAssured_TestCases_PL2.java:131)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- searchPatientTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="BookingListTest" time="2.019">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.BookingListTest(RestAssured_TestCases_PL2.java:182)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- BookingListTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="MainStoreTest" time="0.003">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.MainStoreTest(RestAssured_TestCases_PL2.java:223)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- MainStoreTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="PharmacyStoreTest" time="0.01">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.PharmacyStoreTest(RestAssured_TestCases_PL2.java:260)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- PharmacyStoreTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="ActivatePharmacyCountTest" time="0.807">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.ActivatePharmacyCountTest(RestAssured_TestCases_PL2.java:308)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- ActivatePharmacyCountTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="DeactivatePharmCountTest" time="0.006">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.DeactivatePharmCountTest(RestAssured_TestCases_PL2.java:342)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- DeactivatePharmCountTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="AppointApplicDeptTest" time="0.003">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.AppointApplicDeptTest(RestAssured_TestCases_PL2.java:376)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- AppointApplicDeptTest -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="AdmittedPatientsData" time="0.001">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.AdmittedPatientsData(RestAssured_TestCases_PL2.java:417)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- AdmittedPatientsData -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="GetProfileDataByEmployeeId" time="2.06">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.GetProfileDataByEmployeeId(RestAssured_TestCases_PL2.java:471)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- GetProfileDataByEmployeeId -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="addANewDepartment" time="0.002">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.addANewDepartment(RestAssured_TestCases_PL2.java:527)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- addANewDepartment -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="GetDepartments" time="0.049">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.GetDepartments(RestAssured_TestCases_PL2.java:561)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- GetDepartments -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="EditDepartment" time="0.757">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.EditDepartment(RestAssured_TestCases_PL2.java:661)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- EditDepartment -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="GetImagingTypes" time="0.02">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.GetImagingTypes(RestAssured_TestCases_PL2.java:701)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- GetImagingTypes -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="GetSignatoriesByDepartment" time="0.003">
    <failure type="java.lang.AssertionError" message="Status code should be 200 OK. expected [200] but found [0]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 OK. expected [200] but found [0]
at testcases.RestAssured_TestCases_PL2.GetSignatoriesByDepartment(RestAssured_TestCases_PL2.java:740)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- GetSignatoriesByDepartment -->
  <testcase classname="testcases.RestAssured_TestCases_PL2" name="cancelAppointmentTest" time="0.0">
    <skipped/>
  </testcase> <!-- cancelAppointmentTest -->
</testsuite> <!-- Test -->
